name: ml
channels:
  - conda-forge
  - defaults
  - anaconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - affine=2.4.0=py310hca03da5_0
  - anyio=4.2.0=py310hca03da5_0
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.2=py310hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h1a28f6b_0
  - arrow-cpp=19.0.0=h0b7d223_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py310hca03da5_0
  - attrs=23.1.0=py310hca03da5_0
  - aws-c-auth=0.6.19=h80987f9_0
  - aws-c-cal=0.5.20=h80987f9_0
  - aws-c-common=0.8.5=h80987f9_0
  - aws-c-compression=0.2.16=h80987f9_0
  - aws-c-event-stream=0.2.15=h313beb8_0
  - aws-c-http=0.6.25=h80987f9_0
  - aws-c-io=0.13.10=h80987f9_0
  - aws-c-mqtt=0.7.13=h80987f9_0
  - aws-c-s3=0.1.51=h80987f9_0
  - aws-c-sdkutils=0.1.6=h80987f9_0
  - aws-checksums=0.1.13=h80987f9_0
  - aws-crt-cpp=0.18.16=h313beb8_0
  - aws-sdk-cpp=1.11.212=hdd7fb2f_0
  - babel=2.11.0=py310hca03da5_0
  - beautifulsoup4=4.12.3=py310hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.6=h7977b18_0
  - bokeh=3.6.2=py310hca03da5_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.3.7=py310hbda83bc_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py310h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - c-blosc2=2.12.0=h7df6c2f_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.16.0=hd886ae0_6
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.16.0=py310h80987f9_1
  - cfitsio=3.470=h7f6438f_7
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310hca03da5_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - cloudpickle=3.0.0=py310hca03da5_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=py310hca03da5_0
  - contextily=1.7.0=pyhd8ed1ab_0
  - contourpy=1.2.0=py310h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - cytoolz=1.0.1=py310h80987f9_0
  - dask=2025.1.0=pyhd8ed1ab_0
  - dask-core=2025.1.0=pyhd8ed1ab_0
  - dav1d=1.2.1=h80987f9_0
  - deap=1.4.3=np20py310h75e2568_0
  - debugpy=1.6.7=py310h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py310hca03da5_0
  - distributed=2025.1.0=pyhd8ed1ab_0
  - entrypoints=0.4=py310hca03da5_0
  - et_xmlfile=1.1.0=py310hca03da5_0
  - exceptiongroup=1.2.0=py310hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h313beb8_0
  - ffmpeg=6.1.1=h4beb5bb_0
  - filelock=3.17.0=py310hca03da5_0
  - folium=0.18.0=pyhd8ed1ab_0
  - fontconfig=2.14.1=hee714a5_2
  - fonttools=4.51.0=py310h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - freexl=2.0.0=ha3de405_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2024.12.0=py310hca03da5_0
  - gdk-pixbuf=2.42.10=h80987f9_1
  - geographiclib=2.1=py310hca03da5_0
  - geopy=2.4.1=py310hca03da5_0
  - geos=3.9.1=hc377ac9_1
  - geotiff=1.7.0=h41f0982_3
  - gettext=0.21.0=h13f89a0_1
  - gflags=2.2.2=h313beb8_1
  - giflib=5.2.2=h80987f9_0
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - glog=0.5.0=h313beb8_1
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py310h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - harfbuzz=4.3.0=he9eebac_2
  - hdbscan=0.8.39=py310h003b70b_0
  - hdf4=4.2.13=h5e329fb_3
  - hdf5=1.12.1=h05c076b_3
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py310hca03da5_0
  - imageio=2.37.0=py310hca03da5_0
  - importlib-metadata=8.5.0=py310hca03da5_0
  - ipykernel=6.28.0=py310hca03da5_0
  - ipyparallel=8.6.1=py310hca03da5_0
  - ipython=8.25.0=py310hca03da5_0
  - ipywidgets=8.1.2=py310hca03da5_0
  - jedi=0.18.1=py310hca03da5_1
  - jinja2=3.1.4=py310hca03da5_0
  - joblib=1.4.2=py310hca03da5_0
  - jpeg=9e=h80987f9_1
  - json-c=0.16=h1a28f6b_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py310hca03da5_0
  - jsonschema-specifications=2023.7.1=py310hca03da5_0
  - jupyter=1.0.0=py310hca03da5_9
  - jupyter-lsp=2.2.0=py310hca03da5_0
  - jupyter_client=8.6.0=py310hca03da5_0
  - jupyter_console=6.6.3=py310hca03da5_0
  - jupyter_core=5.7.2=py310hca03da5_0
  - jupyter_events=0.10.0=py310hca03da5_0
  - jupyter_server=2.14.1=py310hca03da5_0
  - jupyter_server_terminals=0.4.4=py310hca03da5_1
  - jupyterlab=4.0.11=py310hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py310hca03da5_0
  - jupyterlab_widgets=3.0.10=py310hca03da5_0
  - kealib=1.5.0=hba2eb73_1
  - kiwisolver=1.4.4=py310h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lazy_loader=0.4=py310hca03da5_0
  - lcms2=2.12=hba8e193_0
  - leptonica=1.82.0=h18c3764_2
  - lerc=3.0=hc377ac9_0
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libarchive=3.6.2=h62fee54_3
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.11.1=hde089ae_0
  - libcxx=18.1.8=h5a72898_2
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_1
  - libgdal=3.6.2=h0413ea8_4
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libgrpc=1.62.2=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - libkml=1.3.0=hc4d7c42_7
  - libllvm14=14.0.6=h7ec7a93_3
  - libnetcdf=4.8.1=h0fce390_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.39=h80987f9_0
  - libpq=12.17=h02f6b3c_0
  - libprotobuf=4.25.3=h514c7bf_0
  - librsvg=2.54.4=hb3bd4c3_3
  - libsodium=1.0.18=h1a28f6b_0
  - libspatialite=5.1.0=h87e580a_0
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.1=h3e2b118_0
  - libtheora=1.1.1=h1a28f6b_3
  - libthrift=0.15.0=h73c2103_2
  - libtiff=4.5.1=h313beb8_0
  - libtorch=2.5.1=gpu_mps_h82d5d13_202
  - libuv=1.48.0=h80987f9_0
  - libvorbis=1.3.7=h1a28f6b_0
  - libvpx=1.13.1=h313beb8_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxgboost=2.1.4=cpu_hf17a1b1_0
  - libxml2=2.10.4=h0b34f26_2
  - libzip=1.8.0=h62fee54_1
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=18.1.8=hde57baf_0
  - llvmlite=0.43.0=py310h313beb8_0
  - locket=1.0.0=py310hca03da5_0
  - lz4=4.3.2=py310h80987f9_1
  - lz4-c=1.9.4=h313beb8_1
  - lzo=2.10=h1a28f6b_2
  - markupsafe=2.1.3=py310h80987f9_0
  - matplotlib=3.8.4=py310hca03da5_0
  - matplotlib-base=3.8.4=py310h46d7db6_0
  - matplotlib-inline=0.1.6=py310hca03da5_0
  - mercantile=1.2.1=pyhd8ed1ab_1
  - minizip=4.0.3=ha89c15f_0
  - missingno=0.5.2=pyhd8ed1ab_0
  - mistune=2.0.4=py310hca03da5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py310hca03da5_0
  - msgpack-python=1.0.3=py310h525c30c_0
  - mysql=5.7.24=ha71a6ea_2
  - nbclient=0.8.0=py310hca03da5_0
  - nbconvert=7.10.0=py310hca03da5_0
  - nbformat=5.9.2=py310hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py310hca03da5_0
  - networkx=3.4.2=py310hca03da5_0
  - nomkl=3.0=0
  - notebook=7.0.8=py310hca03da5_0
  - notebook-shim=0.2.3=py310hca03da5_0
  - nspr=4.37=hd3a7ab8_0
  - nss=3.89.1=h313beb8_0
  - numba=0.60.0=py310h313beb8_0
  - numexpr=2.8.7=py310hecc3335_0
  - numpy=1.26.4=py310h3b2db8e_0
  - numpy-base=1.26.4=py310ha9811e2_0
  - openh264=2.1.1=h98b2900_0
  - openjpeg=2.4.0=h0ed58ac_1
  - openpyxl=3.1.5=py310h80987f9_0
  - openssl=3.6.0=h5503f6c_0
  - opentelemetry-api=1.30.0=py310hca03da5_0
  - orc=2.0.1=h937ddfc_0
  - overrides=7.4.0=py310hca03da5_0
  - packaging=23.2=py310hca03da5_0
  - pandas=2.2.2=py310h313beb8_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h7271ec9_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.2=py310hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.3.0=py310h80987f9_0
  - pip=24.0=py310hca03da5_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=3.10.0=py310hca03da5_0
  - plotly=5.22.0=py310h33ce5c2_0
  - ply=3.11=py310hca03da5_0
  - poppler=22.12.0=h52f4003_3
  - poppler-data=0.4.12=hca03da5_0
  - proj=9.3.1=h805f6d4_0
  - prometheus_client=0.14.1=py310hca03da5_0
  - prompt-toolkit=3.0.43=py310hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=9.0.0=py310hca03da5_0
  - py-xgboost=2.1.4=cpu_pyh43b6f25_0
  - pyarrow=19.0.0=py310h313beb8_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310hca03da5_1
  - pynndescent=0.5.13=pyhff2d567_0
  - pyparsing=3.0.9=py310hca03da5_0
  - pyproj=3.6.1=py310h486faf3_5
  - pyqt=5.15.10=py310h313beb8_0
  - pyqt5-sip=12.13.0=py310h80987f9_0
  - pysocks=1.7.1=py310hca03da5_0
  - pytables=3.10.1=py310h2f855a9_0
  - python=3.10.9=h3ba56d0_0_cpython
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-fastjsonschema=2.16.2=py310hca03da5_0
  - python-json-logger=2.0.7=py310hca03da5_0
  - python-lmdb=1.6.2=py310h313beb8_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=4_cp310
  - pytorch=2.5.1=gpu_mps_py310h80af30b_202
  - pytz=2024.1=py310hca03da5_0
  - pyyaml=6.0.1=py310h80987f9_0
  - pyzmq=25.1.2=py310h313beb8_0
  - qhull=2020.2=h48ca7d4_2
  - qt-main=5.15.2=h0917680_10
  - qtconsole=5.5.1=py310hca03da5_0
  - qtpy=2.4.1=py310hca03da5_0
  - rasterio=1.4.3=py310h9ce171c_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py310hca03da5_0
  - requests=2.32.2=py310hca03da5_0
  - rfc3339-validator=0.1.4=py310hca03da5_0
  - rfc3986-validator=0.1.1=py310hca03da5_0
  - rpds-py=0.10.6=py310hf0e4da2_0
  - scikit-image=0.25.2=py310h6e33161_0
  - scikit-learn=1.4.2=py310h46d7db6_1
  - scipy=1.13.1=py310hd336fd7_0
  - seaborn=0.13.2=py310hca03da5_0
  - send2trash=1.8.2=py310hca03da5_0
  - setuptools=69.5.1=py310hca03da5_0
  - sip=6.7.12=py310h313beb8_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h80987f9_2
  - snappy=1.2.1=h313beb8_0
  - sniffio=1.3.0=py310hca03da5_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py310hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.14.0=py310hca03da5_0
  - tbb=2021.10.0=h1995070_2
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.2.2=py310hca03da5_0
  - terminado=0.17.1=py310hca03da5_0
  - tesseract=5.2.0=hc377ac9_0
  - threadpoolctl=3.5.0=py310h33ce5c2_0
  - tifffile=2024.12.12=py310hca03da5_0
  - tiledb=2.3.3=hb4a6b97_3
  - tinycss2=1.2.1=py310hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tomli=2.0.1=py310hca03da5_0
  - toolz=1.0.0=py310hca03da5_0
  - torchaudio=2.5.1=py310h46d7db6_0
  - torchvision=0.20.1=mps_py310h620d032_102
  - tornado=6.4.1=py310h80987f9_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=py310hca03da5_0
  - typing-extensions=4.11.0=py310hca03da5_0
  - typing_extensions=4.11.0=py310hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - umap-learn=0.5.6=py310hbe9552e_1
  - unicodedata2=15.1.0=py310h80987f9_0
  - uriparser=0.9.8=h2942776_0
  - urllib3=2.2.2=py310hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - utm=0.7.0=pyhd8ed1ab_0
  - watermark=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310hca03da5_1
  - websocket-client=1.8.0=py310hca03da5_0
  - wheel=0.43.0=py310hca03da5_0
  - widgetsnbextension=4.0.10=py310hca03da5_0
  - wrapt=1.17.0=py310h80987f9_0
  - xerces-c=3.2.4=h313beb8_1
  - xgboost=2.1.4=cpu_pyhc1a9e11_0
  - xlrd=2.0.2=pyhd3eb1b0_0
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zict=3.0.0=py310hca03da5_0
  - zipp=3.21.0=py310hca03da5_0
  - zlib=1.2.13=hfb2fe0b_6
  - zlib-ng=2.0.7=h80987f9_0
  - zstd=1.5.5=hd90d995_2
  - pip:
      - arrow==1.3.0
      - fqdn==1.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - ipython-genutils==0.2.0
      - isoduration==20.11.0
      - jsonpointer==3.0.0
      - jupyter-contrib-core==0.4.2
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-server-mathjax==0.2.6
      - kneed==0.8.5
      - lxml==5.3.0
      - nbdime==4.0.2
      - shapely==2.1.2
      - smmap==5.0.2
      - types-python-dateutil==2.9.0.20241206
      - uri-template==1.3.0
      - webcolors==24.11.1
prefix: /opt/anaconda3/envs/ml
